package com.example.nebeng.feature_a_homepage.domain.session.customer.nebeng_motor

import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.CustomerCurrentCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerPricingCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerRideBookingCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerRideCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerTransactionCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PaymentMethodCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.TerminalArrivalCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.TerminalDepartureCustomer

data class BookingSession(
    // =========================
    // CUSTOMER DATA (STATIC)
    // =========================
    val customer: CustomerCurrentCustomer? = null,

    // =========================
    // STATIC LIST FROM BACKEND
    // =========================
    val listPassengerRides: List<PassengerRideCustomer> = emptyList(),
    val listTerminals: List<TerminalDepartureCustomer> = emptyList(), // mapping arrival/departure via aggregator
    val listPaymentMethods: List<PaymentMethodCustomer> = emptyList(),
    val listPassengerPricing: List<PassengerPricingCustomer> = emptyList(),

    // =========================
    // PROGRESS (USER CHOICES)
    // =========================
    val selectedRide:   PassengerRideCustomer? = null,
    val selectedDepartureTerminal: TerminalDepartureCustomer? = null,
    val selectedArrivalTerminal:   TerminalArrivalCustomer? = null,
    val selectedPricing: PassengerPricingCustomer? = null,
    val selectedPaymentMethod: PaymentMethodCustomer? = null,

    val totalPrice: Int = 0,

    val step: BookingStep = BookingStep.SELECT_RIDE,

    // =========================
    // GENERATED BY BACKEND
    // =========================
    val booking: PassengerRideBookingCustomer? = null,
    val transaction: PassengerTransactionCustomer? = null
)
