package com.example.nebeng.feature_passenger_ride_booking.domain.model

data class Driver(
    val id: Int,
    val userId: Int,
    val fullName: String,
    val telephone: String,
    val fullAddress: String,
    val profileImg: String?,
    val faceImg: String?,
    val faceWithIdImg: String?,
    val idCardImg: String?,
    val idCardFullname: String,
    val idCardNumber: String,
    val idCardBirthdate: String,
    val driverLicenseNumber: String,
    val driverLicenseType: String,
    val driverLicenseExpired: String,
    val driverLicenseImg: String?,
    val policeClearanceCertificateNumber: String,
    val policeClearanceCertificateFullname: String,
    val policeClearanceCertificateImg: String?,
    val policeClearanceCertificateExpired: String,
    val idCardVerified: Boolean,
    val driverLicenseVerified: Boolean,
    val policeClearanceVerified: Boolean,
    val creditScore: Int,
    val balance: Int,
    val totalRating: Int,
    val averageRating: Double,
    val ratingCount: Int,
    val createdAt: String,
    val updatedAt: String
)